name: placeme
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 6.0.1
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  font_awesome_flutter: ^10.9.1
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  google_maps_flutter: ^2.13.1
  custom_info_window: ^1.0.1
  provider: ^6.1.1
  logging: ^1.2.0
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/marker.png
    - assets/images/default_avatar.png
    - assets/images/book_cover.png
    - assets/images/applogo1.png
    - assets/images/googlelog.png
    - assets/images/facebooklog.png
    - assets/images/bg.png

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/app_logo.png"
  android: true
  ios: true
  web: false
